### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by ndo277** [catscradleio/catscradle.io#46]
Working on deploying the master branch to heroku

Got to this part in the instructions towards the end: 
![Screen Shot 2019-05-13 at 8 32 15 PM](https://user-images.githubusercontent.com/44879621/57669197-d9cf7a80-75be-11e9-9444-6e1a4451511e.png)
and wasn't able to git push to remote after committing. Got this error:
![Screen Shot 2019-05-13 at 8 33 15 PM](https://user-images.githubusercontent.com/44879621/57669235-f8357600-75be-11e9-91a2-5e5c05b3dc0a.png)

**Comment by yucho** [comment]
@ndo277 Man, you just added another reason why I hate Heroku. First of all, looks like you tried to push `develop` to Heroku. You're supposed to push `master`. But even then, seems like Heroku doesn't support pushing protected branch. Bummer.

I will unprotect `master` and keep it unprotected from now on.

**Comment by ndo277** [comment]
@yucho I'm gonna redo this since @kvebox just cleaned up the user auth a bit with 'feat/fix-routes' and I think we should use that for master branch. I just pulled that branch into develop and merged into master. Trying to deploy the master branch now. 

FYI @demetrios711

**Comment by ndo277** [comment]
We are live! 

https://thawing-headland-67225.herokuapp.com/#/

We can update the url later.
